name: CI/CD Pipeline

on:
  push:
    branches:
      - develop/github-actions
      - main
  pull_request:
    branches:
      - develop/github-actions

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x] # Specify the Node.js versions to test against
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Cache npm dependencies

      - name: Install dependencies
        run: npm ci # Clean install of dependencies

      - name: Build the project
        run: npm run build --if-present # Build the project if a build script is present

      - name: Clean up existing artifacts
        run: |
          echo "Cleaning up any existing artifacts..."
          if [[ -d dist ]]; then
            rm -rf dist/*  # Remove files in the dist directory
          fi

      - name: Upload built files
        if: github.ref == 'refs/heads/main'
        id: upload
        uses: actions/upload-pages-artifact@v3 # Upload the built artifacts
        with:
          path: dist

      - name: Cleanup
        run: |
          rm -rf venv  # Clean up virtual environment if applicable
          rm -rf ${{ github.event.repository.name }}  # Remove specific directories if needed

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build

    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
